### PR TITLE
Content fixes

### PR DESCRIPTION
**Pull request by jjenzz**
While reading through the handbook I spotted a few minor errors that this PR fixes.

### CODE REVIEW

**Review by yoshuawuyts — APPROVED** [review]
Thanks so much for this PR! - I totally missed it, sorry for not noticing sooner 😰 - we're doing a rewrite tho for the new choo, but merging anyway yay! :sparkles:

**Comment by jjenzz** [comment]
Thanks @yoshuawuyts, and my pleasure 😊

Sorry to derail the PR but how do I follow progress on the rewrite? Would love to see where it's headed.

**Comment by bcomnes** [comment]
Live preview https://handbook.choo.io and content living in https://github.com/yoshuawuyts/choo-handbook/tree/your-first-choo-app

**Comment by jjenzz** [comment]
Thanks, I actually spotted the blog on medium after posting 😳. Sorry!

**Comment by bcomnes** [comment]
No foul no harm take it back! 😝

**Pull request merged**
